# Generated by Django 5.2.7 on 2025-10-22 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='La identificación debe tener entre 4 y 24 caracteres alfanuméricos, guiones o guiones bajos, y debe comenzar con una letra o número.', regex='^[A-Za-z0-9][A-Za-z0-9-_]{3,23}$')], verbose_name='Identificación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Número Celular')),
                ('address', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='La dirección debe tener entre 6 y 80 caracteres y solo puede contener letras, números, espacios y los símbolos: # - . , ñ.', regex='^[a-zA-Z0-9\\s\\-\\#\\.\\,ñÑ]{6,80}$')], verbose_name='Dirección de Residencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
