# Generated by Django 5.2.7 on 2025-11-03 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Número Celular'),
        ),
    ]
