# Generated by Django 5.2.7 on 2025-12-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('director', 'Director'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
