from django.urls import path, include
from rest_framework import routers
from users import views


# Initialize the DefaultRouter provided by Django REST Framework.
# The router automatically generates URL patterns for standard CRUD operations (list, retrieve, create, update, destroy).
router = routers.DefaultRouter()


# Register the UserView (likely a ViewSet) with the router.
# - r'users': Base URL prefix for all operations (e.g., /api/v1/users/)
# - views.UserView: The ViewSet class to handle requests
# - 'users': The base name for the URL patterns (used for reverse lookup)
router.register(r'users', views.UserView, 'users')


# Define the final URL patterns.
urlpatterns = [
    # Includes all URLs generated by the router under the API version prefix.
    # All user endpoints will start with /api/v1/users/
    path("api/v1/", include(router.urls))
]
