# Generated by Django 5.2.7 on 2025-10-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_alter_matricula_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='nombre_perro',
            new_name='nombre_canino',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='servicio',
        ),
        migrations.AddField(
            model_name='matricula',
            name='plan',
            field=models.CharField(choices=[('1_mes', '1 mes'), ('1_bimestre', '1 bimestre'), ('1_trimestre', '1 trimestre'), ('6_meses', '6 meses'), ('1_anio', '1 año')], default='1_mes', max_length=20),
        ),
        migrations.AddField(
            model_name='matricula',
            name='tamano',
            field=models.CharField(choices=[('mini', 'Mini'), ('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=20),
        ),
        migrations.AddField(
            model_name='matricula',
            name='transporte',
            field=models.CharField(choices=[('completo', 'Completo'), ('medio', 'Medio (solo mañana o tarde)'), ('sin_transporte', 'Sin transporte')], default='sin_transporte', max_length=20),
        ),
    ]
