# Generated by Django 5.2.7 on 2025-12-05 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='nombre_canino',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='tamano',
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.CreateModel(
            name='Canino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.ImageField(upload_to='', verbose_name='Edad (en años)')),
                ('tamano', models.CharField(choices=[('mini', 'Mini'), ('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=20)),
                ('observaciones_medicas', models.TextField(blank=True, verbose_name='Notas Médicas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caninos', to=settings.AUTH_USER_MODEL, verbose_name='Dueño/Cliente')),
            ],
            options={
                'verbose_name': 'Canino',
                'verbose_name_plural': 'Caninos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='canino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_activas', to='matriculas.canino'),
        ),
    ]
