# Generated by Django 5.2.7 on 2025-12-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_remove_matricula_edad_remove_matricula_nombre_canino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='edad',
            field=models.PositiveIntegerField(verbose_name='Edad (en años)'),
        ),
    ]
